baseURL = 'https://double-tilde.com/'
languageCode = 'en-gb'
title = 'Double Tilde'

[outputs]
  home = ['html']
  section = ['html', 'rss']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = 'about'
    url = '/about'
    weight = 10

  [[menus.main]]
    name = 'Articles'
    pageRef="articles"
    url = '/articles'
    weight = 20

  [[menus.main]]
    name = 'Contact'
    pageRef = 'contact'
    url = '/about/#contact'
    weight = 30

  [[menus.footer]]
    name = 'Home'
    pageRef = 'home'
    url = '/'
    weight = 10

  [[menus.footer]]
    name = 'About'
    pageRef = 'about'
    url = '/about'
    weight = 20

  [[menus.footer]]
    name = 'Projects'
    pageRef = 'projects'
    url = '/about/#projects'
    weight = 30

  [[menus.footer]]
    name = 'Back to Top'
    pageRef = 'back to top'
    url = '#main'
    weight = 40

  [[menus.footer]]
    name = 'RSS Feed'
    pageRef = 'rss feed'
    url = '/articles/index.xml'
    weight = 50

  [[menus.footer]]
    name = 'Reading Log'
    pageRef = 'reading log'
    url = '/reading-log'
    weight = 60

  [[menus.footer]]
    name = 'Notes'
    pageRef = 'notes'
    url = '/notes'
    weight = 70

[params]
  math = true

  [params.socials]
    [[params.socials.entry]]
      logo = "at-sign"
      label = "Bluesky"
      href = "https://bsky.app/profile/double-tilde.bsky.social"

    [[params.socials.entry]]
      logo = "github"
      label = "Github"
      href = "https://github.com/double-tilde"

    [[params.socials.entry]]
      logo = "gitlab"
      label = "Gitlab"
      href = "https://gitlab.com/double-tilde"

    [[params.socials.entry]]
      logo = "linkedin"
      label = "Linkedin"
      href = "https://www.linkedin.com/in/amy-dt/"

    [[params.socials.entry]]
      logo = "youtube"
      label = "YouTube (coming soon)"
      href = "https://youtube.com"



  [params.projects]
    [[params.projects.entry]]
      title = "Double Tilde Website"
      source = "https://github.com/double-tilde/site"
      description = ["I started creating this site in the summer of 2025, I had previously gone back and fourth on creating a website for a few years, since a lot of people use the internet as a way to access social media, so I would find myself discouraged to maintain a personal site.", "However, I think it is important to contribute to the internet you want to have rather than the one that currently exists, your website may never reach as many people as Reddit or TikTok, but those that read your site will often appreciate your articles much more than your comments in a sea of other users and bots.", "I used this project as a way to start writing articles, I aim to write 1-2 per month. I decided to build it with Hugo, which is a static site framework built with Go, the syntax is simple and has a lot of built in features useful for templating like render hooks and shortcodes.", "The name for my website comes from my interest in philosophy, logic, and programming. The double tilde sign is used for approximation and negation in these subjects, it also looks cool as a logo."]
      image = "/images/project-double-tilde-site.svg"
      date = "2025-10-01"
      tech = ["Hugo", "CSS", "JavaScript", "SSG"]

  [params.education]
    [[params.education.entry]]
      title = "Supervised Machine Learning Certificate"
      description = "The second course I took via WatSPEED was focused on a specific area of machine learning. The supervised machine learning course was eight weeks and explored various techniques, including algorithms of regression (linear and logical) and classification (Na√Øve Bayes, k-NN), model performance, feature selection, tree-based methods and support vector machines. We then used these models in Python. Next, we compared the performance of the classification models and implemented various cross-validation techniques. We applied feature selection, shrinkage methods and support vector machines and learnt about the benefits of these different techniques. Finally, we applied tree-based methods to the regression and classification models. Learning about the specific area of supervised machine learning made ML feel more approachable as a whole."
      date = "2025-12-22"
      org = "University of Waterloo Watspeed"

    [[params.education.entry]]
      title = "Python For Machine Learning Certificate"
      description = "Through my position as a web designer, I was able to take WatSPEED courses, shorter programs available through the University of Waterloo. I decided to look into machine learning. I completed a seven week course that focused on the foundational skills for machine learning such as terminology, methods, and best practices for data preparation. The course covered how to apply data manipulation techniques to prepare data sets, how to handle missing values, duplicates, categorical data, and outliers. We then moved on to splitting a data set into training and test sets and then used feature scaling methods to transform the data. We finally created data visualizations using Seaborn, Matplotlib, and Pandas and explored the challenges of using certain models. Overall, I gained a broader understanding of machine learning and what it can be used for."
      date = "2025-07-25"
      org = "University of Waterloo Watspeed"

    [[params.education.entry]]
      title = "Diploma of Higher Education"
      description = "I Studied Philosophy for 2 years at UEA. Whilst studying I improved my communication skills, learnt how to understand other points of view and critique them, and how to formulate good questions to solve problems. My favourite subject was Propositional Logic, the study of calculating an argument's validity using equations."
      date = "2018-05-01"
      org = "University of East Anglia"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        title = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
  [markup.highlight]
    style = 'github-dark'

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 80
